apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-playground
  template:
    metadata:
      labels:
        app: my-playground
    spec:
      containers:
        - name: my-playground
          image: valarmo3/playground:v1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: my-playground
  namespace: dev
spec:
  selector:
    app: my-playground
  ports:
    - port: 8888
      targetPort: 8888
